# Generated by Django 5.0.7 on 2024-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tgnick",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Укажите город",
                max_length=100,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
