# Generated by Django 5.0.7 on 2024-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_donat"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID чата в Телеграм",
                max_length=255,
                null=True,
                verbose_name="ID чата в Телеграм",
            ),
        ),
    ]
