# Generated by Django 5.1 on 2024-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_car_owner_moto_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="amount",
            field=models.IntegerField(default=1000, verbose_name="Цена"),
        ),
    ]
